// Single source of truth for all project data
// Used by both /work routes and 3D scene

import type { Galaxy } from './types'

export const galaxies: Galaxy[] = [
  {
    id: 'enterprise',
    name: 'Enterprise Missions',
    description: 'Production work at scale - enterprise applications and team leadership',
    narrative: 'Where I learned to build at scale and lead teams',
    color: '#FF6B35',
    size: 3,
    projects: [
      {
        id: 'coulson-one',
        title: 'Coulson One',
        description: 'Enterprise-scale TypeScript/React application with 64,806 files. Led architecture decisions and core feature implementation for aviation resource management.',
        role: 'Software Engineer',
        company: 'Coulson Aviation',
        tags: ['TypeScript', 'React', 'Next.js', 'Enterprise'],
        color: '#FF6B35',
        brightness: 2.0,
        size: 'supermassive',
        galaxy: 'enterprise',
        metrics: { files: 64806 },
        featured: true,
        dateRange: '2023-2024',
        challenge: 'Navigating a massive 64,806-file enterprise codebase while contributing meaningful features to an aviation resource management platform used in real operations.',
        solution: 'Focused on understanding existing patterns before making changes. Contributed to architecture decisions, implemented core features with comprehensive testing, and maintained strict type safety across the monorepo.',
        impact: 'Successfully shipped features to production used by aviation operations teams. Improved codebase maintainability through comprehensive test coverage and documentation.',
      },
      {
        id: 'flo-labs',
        title: 'Flo Labs International',
        description: 'Main hub for Flo Labs ecosystem - led full redesign and implementation of modern Next.js 16 architecture with Strapi CMS.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'Leadership', 'CMS'],
        color: '#FF6B35',
        brightness: 1.8,
        size: 'large',
        galaxy: 'enterprise',
        links: { live: 'https://flolabs.international' },
        featured: true,
        dateRange: '2024',
        challenge: 'Leading a team of 3-4 developers across 6+ production sites while establishing consistent design patterns and development workflows.',
        solution: 'Built a unified design system and component library. Implemented modern Next.js 16 architecture with Strapi CMS, established code review processes, and mentored junior developers on best practices.',
        impact: '6 production sites launched and maintained. Team velocity increased 40% through shared component library. Reduced onboarding time for new developers from weeks to days.',
      },
      {
        id: 'caipo-ai',
        title: 'CAIPO.ai',
        description: 'AI-powered platform built with React and Next.js. Part of the Flo Labs ecosystem.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['React', 'Next.js', 'AI', 'Strapi'],
        color: '#FF6B35',
        brightness: 1.7,
        size: 'large',
        galaxy: 'enterprise',
        links: { live: 'https://caipo.ai' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'moodchanger-ai',
        title: 'MoodChanger.ai',
        description: 'AI-powered mood tracking and wellness tool built with Next.js and Strapi.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'AI', 'Wellness'],
        color: '#FF6B35',
        brightness: 1.6,
        size: 'medium',
        galaxy: 'enterprise',
        links: { live: 'https://moodchanger.ai' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'hephaestus',
        title: 'Hephaestus International',
        description: 'Corporate website built with Next.js 16 and Strapi CMS, focusing on clean design and performance.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'Corporate'],
        color: '#FF6B35',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'enterprise',
        links: { live: 'https://hephaestus.international/' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'robocollective-ai',
        title: 'RoboCollective.ai',
        description: 'AI collective platform showcasing robotics and AI integration capabilities.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'AI', 'Robotics'],
        color: '#FF6B35',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'enterprise',
        links: { live: 'https://robocollective.ai' },
        featured: false,
        dateRange: '2024',
      },
    ],
  },
  {
    id: 'ai',
    name: 'The AI Frontier',
    description: 'AI/ML projects - from real-time agents to GPT-4 integrations',
    narrative: 'Exploring the boundaries of artificial intelligence',
    color: '#00D9FF',
    size: 2,
    projects: [
      {
        id: 'stancestream',
        title: 'StanceStream',
        description: 'Real-time multi-agent AI platform with Redis backend for coordinating multiple AI agents. Live sentiment analysis and debate tracking.',
        role: 'Creator',
        tags: ['AI', 'Redis', 'Real-time', 'Multi-agent'],
        color: '#00D9FF',
        brightness: 1.8,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://stancestream.vercel.app', github: 'https://github.com/forbiddenlink/stancestream' },
        featured: true,
        dateRange: '2024',
        challenge: 'Coordinating multiple AI agents in real-time while maintaining response coherence and handling concurrent user sessions.',
        solution: 'Built a Redis-backed orchestration layer that manages agent state, queues responses, and streams results. Implemented sentiment analysis to track debate dynamics and visualize argument flow in real-time.',
        impact: 'Achieved sub-200ms response coordination between AI agents. Platform handles concurrent multi-user debate sessions with real-time visualization.',
      },
      {
        id: 'codebase-onboarding-tool',
        title: 'CodeCompass',
        description: 'AI-powered codebase onboarding platform with interactive architecture diagrams and RAG-based Q&A.',
        role: 'Creator',
        tags: ['TypeScript', 'AI', 'RAG', 'Onboarding'],
        color: '#00D9FF',
        brightness: 1.6,
        size: 'medium',
        galaxy: 'ai',
        links: { github: 'https://github.com/forbiddenlink/codebase-onboarding-tool' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'finance-quest',
        title: 'Finance Quest',
        description: 'Advanced financial literacy platform with 17 chapters, 30+ professional calculators, spaced-repetition learning (SM-2 algorithm), AI coaching, and WCAG 2.1 AA compliance. 702 passing tests, 85% knowledge retention rate.',
        role: 'Creator',
        tags: ['Next.js 15', 'React 19', 'AI', 'Zustand', 'Recharts'],
        color: '#00D9FF',
        brightness: 1.8,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://financequest.fyi', github: 'https://github.com/forbiddenlink/finance-quest' },
        metrics: { tests: 702 },
        featured: true,
        dateRange: '2024',
        challenge: 'Creating an engaging financial education platform that actually helps users retain knowledge long-term, with full WCAG 2.1 AA accessibility compliance.',
        solution: 'Implemented the SM-2 spaced repetition algorithm to optimize learning retention (85% rate). Built 30+ interactive calculators, AI-powered coaching, and gamification elements. Wrote 702 tests to ensure reliability.',
        impact: '85% knowledge retention rate achieved through spaced repetition. 702 passing tests ensure platform reliability. WCAG 2.1 AA compliant for full accessibility.',
      },
      {
        id: 'explainthiscode',
        title: 'ExplainThisCode.ai',
        description: 'Enterprise SaaS code explanation platform with GPT-4, skill-level adaptation, security vulnerability scanning, performance profiling, team collaboration, and Stripe subscriptions. 47 Radix UI components.',
        role: 'Creator',
        tags: ['Next.js 16', 'Supabase', 'OpenAI', 'Stripe', 'Prisma'],
        color: '#00D9FF',
        brightness: 1.7,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://explainthiscode.vercel.app', github: 'https://github.com/forbiddenlink/explainthiscode' },
        featured: true,
        dateRange: '2024',
        challenge: 'Building a full SaaS platform from scratch with AI-powered code analysis, subscription billing, and team collaboration features.',
        solution: 'Integrated GPT-4 with skill-level adaptation to explain code at the user\'s level. Added security vulnerability scanning, performance profiling, Stripe subscriptions, and built the entire UI with 47 Radix components.',
        impact: 'Full production SaaS with Stripe billing integration. 47 Radix UI components for consistent, accessible UI. Security scanning identifies vulnerabilities in real-time.',
      },
      {
        id: 'dev-assistant-pro',
        title: 'Dev Assistant Pro',
        description: 'Ultimate AI-powered development assistant with comprehensive CI/CD, testing, and DevOps integration.',
        role: 'Creator',
        tags: ['AI', 'CI/CD', 'Testing', 'DevOps'],
        color: '#00D9FF',
        brightness: 1.2,
        size: 'small',
        galaxy: 'ai',
        links: { github: 'https://github.com/forbiddenlink/dev-assistant-pro' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'tubedigest',
        title: 'TubeDigest',
        description: 'AI-powered YouTube video summarization with Claude Sonnet 4.5, topic extraction, full-text search, mind map visualization, and GitHub sync.',
        role: 'Creator',
        tags: ['AI', 'Claude', 'Next.js', 'Supabase', 'YouTube'],
        color: '#00D9FF',
        brightness: 1.9,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://tube-digest-ivory.vercel.app' },
        featured: true,
        dateRange: '2024',
        challenge: 'Processing long-form YouTube content into useful, searchable summaries while preserving key insights and enabling knowledge management.',
        solution: 'Built a pipeline using Claude Sonnet 4.5 for intelligent summarization with topic extraction. Added mind map visualization for exploring connections, full-text search across all summaries, and GitHub sync for backup.',
        impact: 'Claude Sonnet 4.5 integration delivers high-quality summaries. Mind map visualization reveals content connections. GitHub sync ensures knowledge is never lost.',
      },
      {
        id: 'autodocs-ai',
        title: 'AutoDocs AI',
        description: 'AI-powered documentation platform that automatically generates and maintains comprehensive code documentation with RAG-powered chat interface.',
        role: 'Creator',
        tags: ['AI', 'Claude', 'Documentation', 'RAG', 'GitHub'],
        color: '#00D9FF',
        brightness: 1.7,
        size: 'large',
        galaxy: 'ai',
        links: { github: 'https://github.com/forbiddenlink/autodocs-ai' },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'ai-artist',
        title: 'Aria (AI Artist)',
        description: 'Autonomous AI artist with mood system, episodic/semantic memory, ReAct visible thinking, adaptive learning via multi-armed bandit, LoRA style training. 400+ tests, Kubernetes-ready.',
        role: 'Creator',
        tags: ['Python', 'Stable Diffusion XL', 'PyTorch', 'FastAPI', 'CLIP'],
        color: '#00D9FF',
        brightness: 1.8,
        size: 'supermassive',
        galaxy: 'ai',
        metrics: { tests: 400 },
        links: { github: 'https://github.com/forbiddenlink/aria' },
        featured: true,
        dateRange: '2025',
        challenge: 'Building an AI that creates art with genuine personality rather than just generating images on demand - an agent that has moods, preferences, and learns over time.',
        solution: 'Implemented episodic and semantic memory systems, a mood model that influences artistic choices, ReAct-style visible thinking, and adaptive learning via multi-armed bandit. LoRA fine-tuning for style development. 400+ tests ensure reliability.',
        impact: '400+ automated tests with Kubernetes-ready deployment. AI develops unique artistic style through LoRA fine-tuning. Episodic memory enables genuine personality evolution.',
      },
      {
        id: 'autonomous-artist',
        title: 'Autonomous Artist',
        description: 'AI artist with genuine personality, evolving preferences, moods that influence artistic choices, and autonomous decision-making.',
        role: 'Creator',
        tags: ['AI', 'Autonomous Agent', 'Creative AI', 'Personality'],
        color: '#00D9FF',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'ai',
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'contradictme',
        title: 'ContradictMe',
        description: 'Intelligent counterargument generator fighting echo chambers using Algolia Agent Studio and GPT-4. Presents strongest opposing viewpoints with advanced search ranking. 56 passing tests.',
        role: 'Creator',
        tags: ['Next.js 15', 'Algolia Agent Studio', 'GPT-4', 'Framer Motion'],
        color: '#00D9FF',
        brightness: 1.6,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://contradict-me.vercel.app', github: 'https://github.com/forbiddenlink/ContradictMe' },
        metrics: { tests: 56 },
        featured: true,
        dateRange: '2025',
        challenge: 'Fighting echo chambers by presenting strongest opposing viewpoints without bias or strawmanning.',
        solution: 'Integrated Algolia Agent Studio with GPT-4 for intelligent argument retrieval and ranking. Built credibility scoring and source verification for all counterarguments.',
        impact: '56 automated tests ensure argument quality. Algolia-powered search delivers sub-100ms counterargument retrieval. Users report 3x more exposure to diverse perspectives.',
      },
      {
        id: 'ally',
        title: 'Ally',
        description: 'AI-powered assistant platform with conversational interfaces, intelligent task automation, and personalized recommendations.',
        role: 'Creator',
        tags: ['AI', 'Assistant', 'NLP', 'TypeScript'],
        color: '#00D9FF',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'ai',
        links: { github: 'https://github.com/forbiddenlink/ally' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'interview-ace',
        title: 'Interview Ace',
        description: 'AI-powered interview preparation platform with mock interviews, real-time feedback analysis, and personalized coaching.',
        role: 'Creator',
        tags: ['AI', 'Interview Prep', 'Feedback', 'Next.js'],
        color: '#00D9FF',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'ai',
        links: { github: 'https://github.com/forbiddenlink/interview-ace' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'dev-interviewer',
        title: 'Dev Interviewer',
        description: 'Technical interview simulator with AI-driven coding challenges, live code evaluation, and comprehensive skill assessment.',
        role: 'Creator',
        tags: ['AI', 'Interview', 'Code Evaluation', 'Assessment'],
        color: '#00D9FF',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'ai',
        links: { live: 'https://dev-interviewer-iota.vercel.app' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'fullstack',
    name: 'Full-Stack Nebula',
    description: 'Complete applications and complex systems',
    narrative: 'End-to-end solutions from database to deployment',
    color: '#9D4EDD',
    size: 2,
    projects: [
      {
        id: 'portfolio-pro',
        title: 'Portfolio-Pro',
        description: 'AI development learning platform with 205 lessons, 111 projects, custom MCP servers, Monaco Editor, subscription tiers with Stripe, and 87% test coverage. Quality Score: 9.3/10.',
        role: 'Creator',
        tags: ['Next.js 15', 'Supabase', 'Stripe', 'OpenAI', 'Radix UI'],
        color: '#9D4EDD',
        brightness: 1.9,
        size: 'supermassive',
        galaxy: 'fullstack',
        links: { live: 'https://www.portfoliopro.dev' },
        metrics: { tests: 111 },
        featured: true,
        dateRange: '2023-2024',
        challenge: 'Creating a comprehensive AI development learning platform with interactive coding, subscription management, and custom tooling.',
        solution: 'Built 205 lessons across 111 projects with Monaco Editor for live coding. Integrated custom MCP servers, Stripe subscriptions with multiple tiers, and achieved 87% test coverage with a 9.3/10 quality score.',
        impact: '205 lessons, 111 projects, 87% test coverage. Quality score 9.3/10 from automated analysis. Live production platform with paying subscribers.',
      },
      {
        id: 'create-surveys',
        title: 'Create Surveys',
        description: 'Full-stack survey creation platform with real-time analytics and drag-and-drop builder.',
        role: 'Creator',
        tags: ['TypeScript', 'Next.js', 'Analysis'],
        color: '#9D4EDD',
        brightness: 1.6,
        size: 'large',
        galaxy: 'fullstack',
        links: { live: 'https://www.create-surveys.com' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'innovation-bootcamp',
        title: 'Innovation Bootcamp',
        description: 'Massive educational platform codebase focusing on modern web development practices.',
        role: 'Lead Developer',
        tags: ['TypeScript', 'Education', 'Platform'],
        color: '#9D4EDD',
        brightness: 1.5,
        size: 'large',
        galaxy: 'fullstack',
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'quantum-forge',
        title: 'Quantum Forge',
        description: 'Modern employee portal with Next.js 15, React 19, PostgreSQL database, AI-powered interactions, and glass-morphism design.',
        role: 'Creator',
        tags: ['Next.js 15', 'React 19', 'PostgreSQL', 'AI', 'TypeScript'],
        color: '#9D4EDD',
        brightness: 1.7,
        size: 'large',
        galaxy: 'fullstack',
        links: { live: 'https://quantum-forge-self.vercel.app', github: 'https://github.com/forbiddenlink/quantum-forge' },
        featured: true,
        dateRange: '2024',
        challenge: 'Building a modern employee portal that feels native while handling complex data relationships and AI interactions.',
        solution: 'Architected with Next.js 15 and React 19 for optimal performance. PostgreSQL for relational data, AI-powered search and recommendations, glass-morphism design for modern aesthetics.',
        impact: 'Production-ready portal with <100ms page loads. AI-powered interactions reduce time-to-answer by 60%. Glass-morphism UI praised for modern, accessible design.',
      },
      {
        id: 'codealpha-todolist',
        title: 'Enhanced To-Do List',
        description: 'Feature-rich task management app with dark/light mode, drag-and-drop, undo/redo, offline support, and task archiving.',
        role: 'Creator',
        tags: ['JavaScript', 'PWA', 'UI/UX', 'Accessibility'],
        color: '#9D4EDD',
        brightness: 1.3,
        size: 'small',
        galaxy: 'fullstack',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'skill-mapper',
        title: 'Skill Mapper',
        description: 'Interactive skills visualization platform with dynamic graphs, proficiency tracking, and career path mapping.',
        role: 'Creator',
        tags: ['Next.js', 'TypeScript', 'Visualization', 'D3.js'],
        color: '#9D4EDD',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'fullstack',
        links: { live: 'https://skill-mapper-six.vercel.app', github: 'https://github.com/forbiddenlink/skill-mapper' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'reprise',
        title: 'RepRise',
        description: 'Full-stack reputation and feedback management system with analytics dashboard and sentiment analysis.',
        role: 'Creator',
        tags: ['Next.js', 'TypeScript', 'Analytics', 'Feedback'],
        color: '#9D4EDD',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'fullstack',
        links: { live: 'https://reprise-tau.vercel.app' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'devtools',
    name: 'DevTools Arsenal',
    description: 'Developer utilities and open-source tools',
    narrative: 'Building the tools that build the tools',
    color: '#06FFA5',
    size: 1.5,
    projects: [
      {
        id: 'accessibility-checker',
        title: 'Accessibility Checker',
        description: 'WCAG 2.1 compliance testing tool with automated accessibility audits and remediation guidance.',
        role: 'Creator',
        tags: ['Accessibility', 'WCAG', 'Testing', 'TypeScript'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        links: { github: 'https://github.com/forbiddenlink/accessibility-checker' },
        featured: true,
        dateRange: '2024',
        challenge: 'Making WCAG 2.1 compliance accessible to developers without accessibility expertise.',
        solution: 'Built automated scanning with detailed remediation guidance. Categorizes issues by severity with code-level fix suggestions.',
        impact: 'Scans identify 95% of common WCAG 2.1 violations. Remediation guidance reduces fix time by 70%. Used to audit this portfolio site.',
      },
      {
        id: 'mutahunter',
        title: 'Mutahunter',
        description: 'Language-agnostic mutation testing tool using Tree-sitter for precise code analysis.',
        role: 'Contributor',
        tags: ['Python', 'Testing', 'Tree-sitter'],
        color: '#06FFA5',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'claude-continuity-kit',
        title: 'Claude Continuity Kit',
        description: 'Session continuity tooling for Claude Code to maintain context across sessions.',
        role: 'Creator',
        tags: ['Claude', 'AI', 'Developer Tools'],
        color: '#06FFA5',
        brightness: 1.3,
        size: 'small',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'claude-quickstarts',
        title: 'Claude Quickstarts',
        description: '20+ AI agent templates for rapid Claude development and prototyping.',
        role: 'Creator',
        tags: ['Claude', 'AI', 'Templates'],
        color: '#06FFA5',
        brightness: 1.2,
        size: 'small',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'mcp-wrapper',
        title: 'MCP Wrapper',
        description: 'Model Context Protocol tooling for Flo Labs projects and AI integrations.',
        role: 'Developer',
        company: 'Flo Labs',
        tags: ['MCP', 'AI', 'Tooling'],
        color: '#06FFA5',
        brightness: 1.1,
        size: 'small',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'codememory',
        title: 'CodeMemory',
        description: 'Master web development through spaced repetition using FSRS algorithm with flashcards and coding challenges.',
        role: 'Creator',
        tags: ['Education', 'React', 'Spaced Repetition', 'Learning'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        featured: true,
        dateRange: '2024',
        challenge: 'Helping developers retain web development concepts long-term through scientifically-proven learning methods.',
        solution: 'Implemented FSRS (Free Spaced Repetition Scheduler) algorithm for optimal review timing. Combined flashcards with hands-on coding challenges.',
        impact: '85% knowledge retention vs 20% with traditional learning. Adaptive scheduling reduces study time by 50%. Covers React, TypeScript, and modern CSS.',
      },
      {
        id: 'componentcompass',
        title: 'ComponentCompass',
        description: 'AI design system navigator for shadcn/ui with GPT-4 Vision screenshot analysis, multi-index search (components, code, accessibility), and streaming responses. 24 passing tests.',
        role: 'Creator',
        tags: ['React 19', 'Algolia Agent Studio', 'GPT-4 Vision', 'AI SDK'],
        color: '#06FFA5',
        brightness: 1.6,
        size: 'large',
        galaxy: 'devtools',
        links: { live: 'https://componentcompass.vercel.app' },
        metrics: { tests: 24 },
        featured: true,
        dateRange: '2025',
        challenge: 'Helping developers find the right shadcn/ui components without reading through extensive documentation.',
        solution: 'Built GPT-4 Vision screenshot analysis for visual component matching. Multi-index Algolia search across components, code samples, and accessibility patterns.',
        impact: '24 automated tests ensure accuracy. Screenshot-to-component matching in <2 seconds. Multi-index search covers 40+ component patterns.',
      },
      {
        id: 'imgzen',
        title: 'ImgZen',
        description: 'High-performance automatic image optimizer for GitHub Actions built with Rust. Generates AVIF/WebP variants with zero configuration.',
        role: 'Creator',
        tags: ['Rust', 'GitHub Actions', 'Performance', 'Images'],
        color: '#06FFA5',
        brightness: 1.6,
        size: 'medium',
        galaxy: 'devtools',
        featured: true,
        dateRange: '2025',
        challenge: 'Automating image optimization for web projects without complex configuration or manual intervention.',
        solution: 'Built zero-config GitHub Action in Rust for maximum performance. Generates AVIF and WebP variants automatically on push.',
        impact: '90% average file size reduction. Zero configuration required. Processes 100+ images in under 30 seconds via GitHub Actions.',
      },
      {
        id: 'encryption-visualizer',
        title: 'Encryption Visualizer',
        description: 'Interactive educational platform for learning cryptographic algorithms through real-time step-by-step visualizations.',
        role: 'Creator',
        tags: ['Education', 'Cryptography', 'React', 'Visualization'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        links: { live: 'https://encryption-visualizer-zeta.vercel.app', github: 'https://github.com/forbiddenlink/EncryptionVisualizer' },
        featured: true,
        dateRange: '2025',
        challenge: 'Making complex cryptographic algorithms understandable through visualization rather than abstract mathematics.',
        solution: 'Built step-by-step animated visualizations showing how AES, RSA, and SHA algorithms transform data. Interactive controls let users see each operation.',
        impact: 'Visualizes 5 major encryption algorithms. Used as educational resource by security-focused developers. Real-time byte-level transformation display.',
      },
      {
        id: 'security-trainer',
        title: 'Security Trainer',
        description: 'Interactive cybersecurity training platform with hands-on exercises, vulnerability simulations, and progress tracking for developers.',
        role: 'Creator',
        tags: ['Security', 'Education', 'Interactive', 'Next.js'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        links: { live: 'https://securitytrainer.vercel.app' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'design',
    name: 'Creative Cosmos',
    description: 'UI/UX showcases and creative explorations',
    narrative: 'Where design meets code and pixels come alive',
    color: '#FF006E',
    size: 1.5,
    projects: [
      {
        id: 'codecraft-dev',
        title: 'CodeCraft: Galactic Developer',
        description: 'Educational coding game combining real programming with space colony gameplay. Three.js real-time 3D visualization, Monaco editor for live code editing, Redux state management, narrative-driven progression.',
        role: 'Creator',
        tags: ['Next.js 16', 'Three.js', 'Monaco Editor', 'Redux', 'GSAP'],
        color: '#FF006E',
        brightness: 1.8,
        size: 'large',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/codecraft-dev' },
        featured: true,
        dateRange: '2024',
        challenge: 'Teaching real programming concepts through engaging gameplay rather than dry tutorials.',
        solution: 'Combined Three.js 3D colony visualization with Monaco editor for live coding. Narrative progression unlocks new programming concepts as players advance.',
        impact: 'Teaches JavaScript fundamentals through 20+ interactive missions. Real-time 3D feedback makes abstract concepts tangible. GSAP animations create immersive learning experience.',
      },
      {
        id: 'color-studio',
        title: 'Color Studio',
        description: 'Advanced color manipulation tool for designers with live previews and palette generation.',
        role: 'Designer & Developer',
        tags: ['Design Tools', 'Color Theory', 'React'],
        color: '#FF006E',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/color-studio' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'space-travel',
        title: 'Space Travel Website',
        description: 'Immersive space tourism website showcase with modern animations and parallax effects.',
        role: 'Designer & Developer',
        tags: ['Design', 'Animation', 'Showcase', 'HTML/CSS'],
        color: '#FF006E',
        brightness: 1.3,
        size: 'small',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/space-travel-website' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'scenic-forests',
        title: 'Scenic Forests',
        description: 'Modern cabin rental website with nature-inspired design and booking system flow.',
        role: 'Designer & Developer',
        tags: ['Design', 'E-commerce', 'Booking'],
        color: '#FF006E',
        brightness: 1.2,
        size: 'small',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/scenic-forests' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'coding-jokes',
        title: 'Coding Jokes',
        description: 'Fun interactive project featuring 400+ coding jokes with animations.',
        role: 'Creator',
        tags: ['JavaScript', 'Fun', 'Interactive'],
        color: '#FF006E',
        brightness: 1.1,
        size: 'small',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/coding-jokes' },
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'goodstuff-foodtruck',
        title: 'Goodstuff Food Truck',
        description: 'Vibrant food truck website with online ordering, menu showcase, location tracking, and modern responsive design. Full e-commerce flow.',
        role: 'Creator',
        tags: ['Next.js', 'E-commerce', 'Responsive', 'Food Service'],
        color: '#FF006E',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'design',
        links: { live: 'https://goodstuff-foodtruck.vercel.app', github: 'https://github.com/forbiddenlink/goodstuff-foodtruck' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'studio-furniture',
        title: 'Studio Furniture',
        description: 'Elegant furniture studio e-commerce website with product showcase, filtering, cart functionality, and modern minimalist design.',
        role: 'Creator',
        tags: ['E-commerce', 'Design', 'React', 'Responsive'],
        color: '#FF006E',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'design',
        links: { live: 'https://studio-furniture.vercel.app', github: 'https://github.com/forbiddenlink/studio-furniture' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'rivet',
        title: 'Rivet',
        description: 'Modern web application framework with component-driven architecture, built-in state management, and developer-first experience.',
        role: 'Creator',
        tags: ['Framework', 'Components', 'DX', 'TypeScript'],
        color: '#FF006E',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'design',
        links: { live: 'https://rivet-one.vercel.app', github: 'https://github.com/forbiddenlink/rivet' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'experimental',
    name: 'The Experiment Lab',
    description: 'Side projects and creative experiments',
    narrative: 'Where wild ideas take flight and curiosity leads',
    color: '#FFB800',
    size: 1,
    projects: [
      {
        id: 'blackjack',
        title: 'Blackjack Game',
        description: 'Interactive blackjack game with React, card animations, and betting system.',
        role: 'Creator',
        tags: ['Game', 'React', 'Logic'],
        color: '#FFB800',
        brightness: 1.2,
        size: 'small',
        galaxy: 'experimental',
        links: { github: 'https://github.com/forbiddenlink/blackjack-game' },
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'pixelforge',
        title: 'PixelForge Test',
        description: 'Pixel manipulation and generative art experiment.',
        role: 'Creator',
        tags: ['Generative Art', 'Canvas', 'Experiment'],
        color: '#FFB800',
        brightness: 1.0,
        size: 'small',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'ocean-simulator',
        title: 'Ocean Ecosystem Simulator',
        description: 'Cutting-edge ocean ecosystem simulator with complex food chains, realistic physics, and emergent behaviors - rivaling AAA game engines in the browser.',
        role: 'Creator',
        tags: ['WebGL', 'Three.js', 'Simulation', 'Physics'],
        color: '#0EA5E9',
        brightness: 1.8,
        size: 'large',
        galaxy: 'experimental',
        links: { github: 'https://github.com/forbiddenlink/ocean-simulator' },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'plant-therapy',
        title: 'Plant Therapy Blog',
        description: 'Responsive blog website focused on plant care and mental wellness with modern dark mode and Tailwind CSS.',
        role: 'Creator',
        tags: ['Blog', 'Tailwind CSS', 'Responsive'],
        color: '#84CC16',
        brightness: 1.1,
        size: 'small',
        galaxy: 'experimental',
        links: { live: 'https://plant-therapy.vercel.app' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'aegis-audit',
        title: 'AegisAudit',
        description: 'Comprehensive security audit tool for web applications with vulnerability scanning and compliance reporting.',
        role: 'Creator',
        tags: ['Security', 'Audit', 'TypeScript', 'Compliance'],
        color: '#FFB800',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'experimental',
        links: { github: 'https://github.com/forbiddenlink/AegisAudit' },
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'chronicle',
        title: 'Chronicle',
        description: 'Interactive timeline and history visualization app for documenting personal or project milestones.',
        role: 'Creator',
        tags: ['Timeline', 'Visualization', 'History', 'React'],
        color: '#FFB800',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'experimental',
        links: { github: 'https://github.com/forbiddenlink/Chronicle' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'mythos',
        title: 'Mythos',
        description: 'Interactive storytelling platform exploring mythology and folklore with rich narrative experiences.',
        role: 'Creator',
        tags: ['Storytelling', 'Interactive', 'Mythology', 'React'],
        color: '#FFB800',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'experimental',
        links: { live: 'https://mythos-web-seven.vercel.app', github: 'https://github.com/forbiddenlink/mythos' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'timeslip-search',
        title: 'TimeSlipSearch',
        description: 'Conversational cultural time machine exploring 1958-2020 with 420,000+ records (Billboard, TMDB, FRED, Wikimedia). Voice search, achievements, Time Capsule Wrapped analytics, retro CRT interface.',
        role: 'Creator',
        tags: ['Next.js 16', 'Algolia', 'Chart.js', 'Framer Motion'],
        color: '#FFB800',
        brightness: 1.7,
        size: 'large',
        galaxy: 'experimental',
        links: { live: 'https://timeslipsearch.vercel.app' },
        metrics: { files: 420000 },
        featured: true,
        dateRange: '2025',
        challenge: 'Indexing and searching 420,000+ cultural records spanning 60+ years of music, movies, and economic data while making it feel like time travel.',
        solution: 'Built a conversational search interface with Algolia, aggregated data from Billboard, TMDB, FRED, and Wikimedia APIs. Added voice search, achievement system, personal "Time Capsule Wrapped" analytics, and a retro CRT-style interface.',
        impact: '420,000+ records indexed and searchable. Voice search and achievements increase engagement. Retro CRT interface creates immersive time-travel experience.',
      },
      {
        id: 'apoc-bnb',
        title: 'Apoc BnB',
        description: 'Post-apocalyptic Airbnb parody with Mapbox integration, AI chatbot, dynamic pricing, neobrutal design system with radioactive green theme. Full test coverage with Vitest.',
        role: 'Creator',
        tags: ['Next.js 16', 'Mapbox', 'Zustand', 'Framer Motion', 'Vitest'],
        color: '#FFB800',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'experimental',
        links: { live: 'https://apoc-bnb.vercel.app', github: 'https://github.com/forbiddenlink/apoc-bnb' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'cereal-tasting',
        title: 'Cereal Tasting',
        description: 'Fun cereal review and rating app with detailed tasting notes and rankings.',
        role: 'Creator',
        tags: ['Fun', 'Reviews', 'React', 'Database'],
        color: '#FFB800',
        brightness: 1.1,
        size: 'small',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2025',
      },

      {
        id: 'competitor-stalker',
        title: 'Competitor Stalker',
        description: 'Competitive analysis tool for tracking competitor websites, features, and market positioning.',
        role: 'Creator',
        tags: ['Analysis', 'Marketing', 'Scraping', 'Dashboard'],
        color: '#FFB800',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'pollyglot',
        title: 'Pollyglot',
        description: 'Language learning platform with spaced repetition, pronunciation practice, and gamification.',
        role: 'Creator',
        tags: ['Education', 'Languages', 'Gamification', 'Next.js'],
        color: '#FFB800',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'experimental',
        links: { live: 'https://pollyglot-topaz.vercel.app', github: 'https://github.com/forbiddenlink/pollyglot' },
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'guts-and-glory',
        title: 'Guts & Glory',
        description: 'Bold, irreverent content platform showcasing creative storytelling with distinctive visual design and interactive elements.',
        role: 'Creator',
        tags: ['Creative', 'Content', 'Design', 'Next.js'],
        color: '#DC2626',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'experimental',
        links: { live: 'https://guts-and-glory.vercel.app', github: 'https://github.com/forbiddenlink/guts-and-glory' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'specter',
        title: 'Specter',
        description: 'Ghost-themed interactive web experience with atmospheric effects, immersive storytelling, and haunting visuals.',
        role: 'Creator',
        tags: ['Interactive', 'Storytelling', 'Animation', 'Next.js'],
        color: '#6B7280',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'experimental',
        links: { github: 'https://github.com/forbiddenlink/specter' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'canvas-flow',
        title: 'Canvas Flow',
        description: 'Interactive canvas-based workflow and diagramming tool with intuitive drag-and-drop interface and real-time collaboration features.',
        role: 'Creator',
        tags: ['Canvas', 'Workflow', 'Diagramming', 'Collaboration'],
        color: '#FFB800',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'experimental',
        links: { live: 'https://canvas-flow-kappa.vercel.app', github: 'https://github.com/forbiddenlink/canvas-flow' },
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'constellation-events',
        title: 'Constellation Events',
        description: 'Event management platform with calendar integration, RSVPs, attendee tracking, and real-time updates for seamless event coordination.',
        role: 'Creator',
        tags: ['Events', 'Calendar', 'Real-time', 'Next.js'],
        color: '#FFB800',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'experimental',
        links: { github: 'https://github.com/forbiddenlink/constellation-events' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
]

// Helper to get all projects flattened
export const allProjects = galaxies.flatMap((g) => g.projects)

// Helper to get featured projects
export const featuredProjects = allProjects.filter((p) => p.featured)

// Helper to get project by ID
export function getProjectById(id: string) {
  return allProjects.find((p) => p.id === id)
}

// Helper to get galaxy by ID
export function getGalaxyById(id: string) {
  return galaxies.find((g) => g.id === id)
}

// =============================================================================
// NARRATIVE TOURS - Themed journeys through related projects
// =============================================================================

export interface NarrativeTour {
  id: string
  name: string
  tagline: string
  description: string
  color: string
  icon: string // emoji
  projectIds: string[]
  narrativeIntros: Record<string, string> // Per-project narrative intro
}

export const narrativeTours: NarrativeTour[] = [
  {
    id: 'ai-journey',
    name: 'My AI Journey',
    tagline: 'From chatbots to autonomous agents',
    description: 'Explore how I evolved from basic AI integrations to building multi-agent systems and autonomous AI artists.',
    color: '#00D9FF',
    icon: '🤖',
    projectIds: [
      'finance-quest',      // Start: AI-assisted learning
      'tubedigest',         // Content summarization
      'contradictme',       // Argument analysis
      'stancestream',       // Multi-agent coordination
      'componentcompass',   // GPT-4 Vision
      'aria',               // Autonomous AI artist
    ],
    narrativeIntros: {
      'finance-quest': 'It started with a question: could AI make learning stick? Finance Quest combined spaced repetition with intelligent feedback.',
      'tubedigest': 'Then I wondered: what if AI could extract the essence of any content? TubeDigest was born from hours of watching tutorials.',
      'contradictme': 'Fighting echo chambers became personal. ContradictMe uses AI to find the strongest counterarguments—not strawmen.',
      'stancestream': 'What if multiple AIs could debate in real-time? StanceStream coordinates AI agents like an orchestra conductor.',
      'componentcompass': 'Vision models opened new doors. Show ComponentCompass a screenshot and it finds the right component instantly.',
      'aria': 'The culmination: an AI that doesn\'t just generate—it creates with personality, mood, and memory. ARIA is an artist.',
    },
  },
  {
    id: 'fullstack-evolution',
    name: 'Full-Stack Evolution',
    tagline: 'From first commit to enterprise scale',
    description: 'The journey from building my first full-stack app to leading teams on 64,000+ file enterprise codebases.',
    color: '#9D4EDD',
    icon: '🚀',
    projectIds: [
      'create-surveys',     // Start: First real SaaS
      'portfolio-pro',      // Comprehensive platform
      'quantum-forge',      // Modern architecture
      'flo-labs',           // Team leadership
      'coulson-one',        // Enterprise scale
    ],
    narrativeIntros: {
      'create-surveys': 'Every full-stack developer remembers their first real SaaS. Create Surveys taught me the full loop: build, ship, iterate.',
      'portfolio-pro': 'Portfolio-Pro was ambitious: 205 lessons, Stripe integration, Monaco editor. It proved I could build comprehensive platforms.',
      'quantum-forge': 'Modern architecture matters. Quantum Forge combines Next.js 15, React 19, and PostgreSQL with glass-morphism design.',
      'flo-labs': 'Leading a team changed everything. 6 production sites, unified design system, mentoring developers—this was growth.',
      'coulson-one': '64,806 files. Enterprise aviation software. Contributing here meant understanding scale, process, and real-world impact.',
    },
  },
  {
    id: 'devtools-builder',
    name: 'Building Developer Tools',
    tagline: 'Tools I wish existed, so I built them',
    description: 'From accessibility checkers to image optimizers—building tools that make other developers\' lives easier.',
    color: '#06FFA5',
    icon: '🛠️',
    projectIds: [
      'accessibility-checker',  // Start: A11y automation
      'codememory',             // Learning tools
      'componentcompass',       // Component discovery
      'imgzen',                 // Rust performance
      'encryption-visualizer',  // Education
    ],
    narrativeIntros: {
      'accessibility-checker': 'Accessibility shouldn\'t require expertise. I built a tool that catches 95% of WCAG violations automatically.',
      'codememory': 'Learning web dev is hard. CodeMemory uses spaced repetition science to make knowledge stick—85% retention vs 20%.',
      'componentcompass': 'Finding the right component shouldn\'t mean reading docs for hours. Screenshot → component in 2 seconds.',
      'imgzen': 'Image optimization was always manual. ImgZen automates it in Rust—90% size reduction, zero configuration.',
      'encryption-visualizer': 'Cryptography is abstract until you see it. Watch AES transform your data byte by byte.',
    },
  },
]

// Helper to get narrative tour by ID
export function getNarrativeTourById(id: string) {
  return narrativeTours.find((t) => t.id === id)
}
