// Single source of truth for all project data
// Used by both /work routes and 3D scene

import type { Galaxy } from './types'

export const galaxies: Galaxy[] = [
  {
    id: 'enterprise',
    name: 'Enterprise Supernova',
    description: 'Production work at scale - enterprise applications and leadership',
    color: '#FF6B35',
    size: 3,
    projects: [
      {
        id: 'coulson-one',
        title: 'Coulson One',
        description: 'Enterprise-scale TypeScript/React application with 64,806 files. Led architecture decisions and core feature implementation for aviation resource management.',
        role: 'Software Engineer',
        company: 'Coulson Aviation',
        tags: ['TypeScript', 'React', 'Next.js', 'Enterprise'],
        color: '#FF6B35',
        brightness: 2.0,
        size: 'supermassive',
        galaxy: 'enterprise',
        metrics: { files: 64806 },
        featured: true,
        dateRange: '2023-2024',
      },
      {
        id: 'flo-labs',
        title: 'Flo Labs International',
        description: 'Main hub for Flo Labs ecosystem - led full redesign and implementation of modern Next.js 16 architecture with Strapi CMS.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'Leadership', 'CMS'],
        color: '#FF6B35',
        brightness: 1.8,
        size: 'large',
        galaxy: 'enterprise',
        links: { live: 'https://flolabs.international' },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'caipo-ai',
        title: 'CAIPO.ai',
        description: 'AI-powered platform built with React and Next.js. Part of the Flo Labs ecosystem.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['React', 'Next.js', 'AI', 'Strapi'],
        color: '#FF6B35',
        brightness: 1.7,
        size: 'large',
        galaxy: 'enterprise',
        links: { live: 'https://caipo.ai' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'moodchanger-ai',
        title: 'MoodChanger.ai',
        description: 'AI-powered mood tracking and wellness tool built with Next.js and Strapi.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'AI', 'Wellness'],
        color: '#FF6B35',
        brightness: 1.6,
        size: 'medium',
        galaxy: 'enterprise',
        links: { live: 'https://moodchanger.ai' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'hephaestus',
        title: 'Hephaestus International',
        description: 'Corporate website built with Next.js 16 and Strapi CMS, focusing on clean design and performance.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'Corporate'],
        color: '#FF6B35',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'enterprise',
        links: { live: 'https://hephaestus.international/' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'robocollective-ai',
        title: 'RoboCollective.ai',
        description: 'AI collective platform showcasing robotics and AI integration capabilities.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'AI', 'Robotics'],
        color: '#FF6B35',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'enterprise',
        links: { live: 'https://robocollective.ai' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'space-ventures',
        title: 'Space Ventures Institute',
        description: 'Educational platform for space technology and ventures, built with Next.js 14 and Strapi.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Next.js', 'Strapi', 'Education'],
        color: '#FF6B35',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'enterprise',
        featured: false,
        dateRange: '2023-2024',
      },
      {
        id: 'tarrl',
        title: 'TARRL',
        description: 'Research website with custom stack implementation.',
        role: 'Design Team Lead',
        company: 'Flo Labs',
        tags: ['Custom', 'Research', 'Experimental'],
        color: '#FF6B35',
        brightness: 1.2,
        size: 'small',
        galaxy: 'enterprise',
        featured: false,
        dateRange: '2024',
      },
    ],
  },
  {
    id: 'ai',
    name: 'AI Constellation',
    description: 'AI/ML projects - from real-time agents to GPT-4 integrations',
    color: '#00D9FF',
    size: 2,
    projects: [
      {
        id: 'stancestream',
        title: 'StanceStream',
        description: 'Real-time multi-agent AI platform with Redis backend for coordinating multiple AI agents. Live sentiment analysis and debate tracking.',
        role: 'Creator',
        tags: ['AI', 'Redis', 'Real-time', 'Multi-agent'],
        color: '#00D9FF',
        brightness: 1.8,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://stancestream.vercel.app', github: 'https://github.com/forbiddenlink/stancestream' },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'codebase-onboarding-tool',
        title: 'CodeCompass',
        description: 'AI-powered codebase onboarding platform with interactive architecture diagrams and RAG-based Q&A.',
        role: 'Creator',
        tags: ['TypeScript', 'AI', 'RAG', 'Onboarding'],
        color: '#00D9FF',
        brightness: 1.6,
        size: 'medium',
        galaxy: 'ai',
        links: { github: 'https://github.com/forbiddenlink/codebase-onboarding-tool' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'finance-quest',
        title: 'Finance Quest',
        description: 'Advanced financial literacy platform with 17 chapters, 30+ professional calculators, spaced-repetition learning (SM-2 algorithm), AI coaching, and WCAG 2.1 AA compliance. 702 passing tests, 85% knowledge retention rate.',
        role: 'Creator',
        tags: ['Next.js 15', 'React 19', 'AI', 'Zustand', 'Recharts'],
        color: '#00D9FF',
        brightness: 1.8,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://financequest.fyi', github: 'https://github.com/forbiddenlink/finance-quest' },
        metrics: { tests: 702 },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'explainthiscode',
        title: 'ExplainThisCode.ai',
        description: 'Enterprise SaaS code explanation platform with GPT-4, skill-level adaptation, security vulnerability scanning, performance profiling, team collaboration, and Stripe subscriptions. 47 Radix UI components.',
        role: 'Creator',
        tags: ['Next.js 16', 'Supabase', 'OpenAI', 'Stripe', 'Prisma'],
        color: '#00D9FF',
        brightness: 1.7,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://explainthiscode.vercel.app', github: 'https://github.com/forbiddenlink/explainthiscode' },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'dev-assistant-pro',
        title: 'Dev Assistant Pro',
        description: 'Ultimate AI-powered development assistant with comprehensive CI/CD, testing, and DevOps integration.',
        role: 'Creator',
        tags: ['AI', 'CI/CD', 'Testing', 'DevOps'],
        color: '#00D9FF',
        brightness: 1.2,
        size: 'small',
        galaxy: 'ai',
        links: { github: 'https://github.com/forbiddenlink/dev-assistant-pro' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'tubedigest',
        title: 'TubeDigest',
        description: 'AI-powered YouTube video summarization with Claude Sonnet 4.5, topic extraction, full-text search, mind map visualization, and GitHub sync.',
        role: 'Creator',
        tags: ['AI', 'Claude', 'Next.js', 'Supabase', 'YouTube'],
        color: '#00D9FF',
        brightness: 1.9,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://tube-digest-ivory.vercel.app' },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'autodocs-ai',
        title: 'AutoDocs AI',
        description: 'AI-powered documentation platform that automatically generates and maintains comprehensive code documentation with RAG-powered chat interface.',
        role: 'Creator',
        tags: ['AI', 'Claude', 'Documentation', 'RAG', 'GitHub'],
        color: '#00D9FF',
        brightness: 1.7,
        size: 'large',
        galaxy: 'ai',
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'ai-artist',
        title: 'Aria (AI Artist)',
        description: 'Autonomous AI artist with mood system, episodic/semantic memory, ReAct visible thinking, adaptive learning via multi-armed bandit, LoRA style training. 400+ tests, Kubernetes-ready.',
        role: 'Creator',
        tags: ['Python', 'Stable Diffusion XL', 'PyTorch', 'FastAPI', 'CLIP'],
        color: '#00D9FF',
        brightness: 1.8,
        size: 'supermassive',
        galaxy: 'ai',
        metrics: { tests: 400 },
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'autonomous-artist',
        title: 'Autonomous Artist',
        description: 'AI artist with genuine personality, evolving preferences, moods that influence artistic choices, and autonomous decision-making.',
        role: 'Creator',
        tags: ['AI', 'Autonomous Agent', 'Creative AI', 'Personality'],
        color: '#00D9FF',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'ai',
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'contradictme',
        title: 'ContradictMe',
        description: 'Intelligent counterargument generator fighting echo chambers using Algolia Agent Studio and GPT-4. Presents strongest opposing viewpoints with advanced search ranking. 56 passing tests.',
        role: 'Creator',
        tags: ['Next.js 15', 'Algolia Agent Studio', 'GPT-4', 'Framer Motion'],
        color: '#00D9FF',
        brightness: 1.6,
        size: 'large',
        galaxy: 'ai',
        links: { live: 'https://contradict-me.vercel.app' },
        metrics: { tests: 56 },
        featured: true,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'fullstack',
    name: 'Full-Stack Nebula',
    description: 'Complete applications and complex systems',
    color: '#9D4EDD',
    size: 2,
    projects: [
      {
        id: 'portfolio-pro',
        title: 'Portfolio-Pro',
        description: 'AI development learning platform with 205 lessons, 111 projects, custom MCP servers, Monaco Editor, subscription tiers with Stripe, and 87% test coverage. Quality Score: 9.3/10.',
        role: 'Creator',
        tags: ['Next.js 15', 'Supabase', 'Stripe', 'OpenAI', 'Radix UI'],
        color: '#9D4EDD',
        brightness: 1.9,
        size: 'supermassive',
        galaxy: 'fullstack',
        links: { live: 'https://www.portfoliopro.dev' },
        metrics: { tests: 111 },
        featured: true,
        dateRange: '2023-2024',
      },
      {
        id: 'create-surveys',
        title: 'Create Surveys',
        description: 'Full-stack survey creation platform with real-time analytics and drag-and-drop builder.',
        role: 'Creator',
        tags: ['TypeScript', 'Next.js', 'Analysis'],
        color: '#9D4EDD',
        brightness: 1.6,
        size: 'large',
        galaxy: 'fullstack',
        links: { live: 'https://www.create-surveys.com' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'innovation-bootcamp',
        title: 'Innovation Bootcamp',
        description: 'Massive educational platform codebase focusing on modern web development practices.',
        role: 'Lead Developer',
        tags: ['TypeScript', 'Education', 'Platform'],
        color: '#9D4EDD',
        brightness: 1.5,
        size: 'large',
        galaxy: 'fullstack',
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'quantum-forge',
        title: 'Quantum Forge',
        description: 'Modern employee portal with Next.js 15, React 19, PostgreSQL database, AI-powered interactions, and glass-morphism design.',
        role: 'Creator',
        tags: ['Next.js 15', 'React 19', 'PostgreSQL', 'AI', 'TypeScript'],
        color: '#9D4EDD',
        brightness: 1.7,
        size: 'large',
        galaxy: 'fullstack',
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'codealpha-todolist',
        title: 'Enhanced To-Do List',
        description: 'Feature-rich task management app with dark/light mode, drag-and-drop, undo/redo, offline support, and task archiving.',
        role: 'Creator',
        tags: ['JavaScript', 'PWA', 'UI/UX', 'Accessibility'],
        color: '#9D4EDD',
        brightness: 1.3,
        size: 'small',
        galaxy: 'fullstack',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'skill-mapper',
        title: 'Skill Mapper',
        description: 'Interactive skills visualization platform with dynamic graphs, proficiency tracking, and career path mapping.',
        role: 'Creator',
        tags: ['Next.js', 'TypeScript', 'Visualization', 'D3.js'],
        color: '#9D4EDD',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'fullstack',
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'reprise',
        title: 'RepRise',
        description: 'Full-stack reputation and feedback management system with analytics dashboard and sentiment analysis.',
        role: 'Creator',
        tags: ['Next.js', 'TypeScript', 'Analytics', 'Feedback'],
        color: '#9D4EDD',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'fullstack',
        links: { live: 'https://reprise-tau.vercel.app' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'devtools',
    name: 'DevTools Sector',
    description: 'Developer utilities and open-source tools',
    color: '#06FFA5',
    size: 1.5,
    projects: [
      {
        id: 'accessibility-checker',
        title: 'Accessibility Checker',
        description: 'WCAG 2.1 compliance testing tool with automated accessibility audits and remediation guidance.',
        role: 'Creator',
        tags: ['Accessibility', 'WCAG', 'Testing', 'TypeScript'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        links: { github: 'https://github.com/forbiddenlink/accessibiliy-checker' },
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'mutahunter',
        title: 'Mutahunter',
        description: 'Language-agnostic mutation testing tool using Tree-sitter for precise code analysis.',
        role: 'Contributor',
        tags: ['Python', 'Testing', 'Tree-sitter'],
        color: '#06FFA5',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'claude-continuity-kit',
        title: 'Claude Continuity Kit',
        description: 'Session continuity tooling for Claude Code to maintain context across sessions.',
        role: 'Creator',
        tags: ['Claude', 'AI', 'Developer Tools'],
        color: '#06FFA5',
        brightness: 1.3,
        size: 'small',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'claude-quickstarts',
        title: 'Claude Quickstarts',
        description: '20+ AI agent templates for rapid Claude development and prototyping.',
        role: 'Creator',
        tags: ['Claude', 'AI', 'Templates'],
        color: '#06FFA5',
        brightness: 1.2,
        size: 'small',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'mcp-wrapper',
        title: 'MCP Wrapper',
        description: 'Model Context Protocol tooling for Flo Labs projects and AI integrations.',
        role: 'Developer',
        company: 'Flo Labs',
        tags: ['MCP', 'AI', 'Tooling'],
        color: '#06FFA5',
        brightness: 1.1,
        size: 'small',
        galaxy: 'devtools',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'codememory',
        title: 'CodeMemory',
        description: 'Master web development through spaced repetition using FSRS algorithm with flashcards and coding challenges.',
        role: 'Creator',
        tags: ['Education', 'React', 'Spaced Repetition', 'Learning'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'componentcompass',
        title: 'ComponentCompass',
        description: 'AI design system navigator for shadcn/ui with GPT-4 Vision screenshot analysis, multi-index search (components, code, accessibility), and streaming responses. 24 passing tests.',
        role: 'Creator',
        tags: ['React 19', 'Algolia Agent Studio', 'GPT-4 Vision', 'AI SDK'],
        color: '#06FFA5',
        brightness: 1.6,
        size: 'large',
        galaxy: 'devtools',
        links: { live: 'https://componentcompass.vercel.app' },
        metrics: { tests: 24 },
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'imgzen',
        title: 'ImgZen',
        description: 'High-performance automatic image optimizer for GitHub Actions built with Rust. Generates AVIF/WebP variants with zero configuration.',
        role: 'Creator',
        tags: ['Rust', 'GitHub Actions', 'Performance', 'Images'],
        color: '#06FFA5',
        brightness: 1.6,
        size: 'medium',
        galaxy: 'devtools',
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'encryption-visualizer',
        title: 'Encryption Visualizer',
        description: 'Interactive educational platform for learning cryptographic algorithms through real-time step-by-step visualizations.',
        role: 'Creator',
        tags: ['Education', 'Cryptography', 'React', 'Visualization'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'security-trainer',
        title: 'Security Trainer',
        description: 'Interactive cybersecurity training platform with hands-on exercises, vulnerability simulations, and progress tracking for developers.',
        role: 'Creator',
        tags: ['Security', 'Education', 'Interactive', 'Next.js'],
        color: '#06FFA5',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'devtools',
        links: { live: 'https://securitytrainer.vercel.app' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'design',
    name: 'Design & Creative Cluster',
    description: 'UI/UX showcases and creative explorations',
    color: '#FF006E',
    size: 1.5,
    projects: [
      {
        id: 'codecraft-dev',
        title: 'CodeCraft: Galactic Developer',
        description: 'Educational coding game combining real programming with space colony gameplay. Three.js real-time 3D visualization, Monaco editor for live code editing, Redux state management, narrative-driven progression.',
        role: 'Creator',
        tags: ['Next.js 16', 'Three.js', 'Monaco Editor', 'Redux', 'GSAP'],
        color: '#FF006E',
        brightness: 1.8,
        size: 'large',
        galaxy: 'design',
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'color-studio',
        title: 'Color Studio',
        description: 'Advanced color manipulation tool for designers with live previews and palette generation.',
        role: 'Designer & Developer',
        tags: ['Design Tools', 'Color Theory', 'React'],
        color: '#FF006E',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/color-studio' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'space-travel',
        title: 'Space Travel Website',
        description: 'Immersive space tourism website showcase with modern animations and parallax effects.',
        role: 'Designer & Developer',
        tags: ['Design', 'Animation', 'Showcase', 'HTML/CSS'],
        color: '#FF006E',
        brightness: 1.3,
        size: 'small',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/space-travel-website' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'scenic-forests',
        title: 'Scenic Forests',
        description: 'Modern cabin rental website with nature-inspired design and booking system flow.',
        role: 'Designer & Developer',
        tags: ['Design', 'E-commerce', 'Booking'],
        color: '#FF006E',
        brightness: 1.2,
        size: 'small',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/scenic-forests' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'coding-jokes',
        title: 'Coding Jokes',
        description: 'Fun interactive project featuring 400+ coding jokes with animations.',
        role: 'Creator',
        tags: ['JavaScript', 'Fun', 'Interactive'],
        color: '#FF006E',
        brightness: 1.1,
        size: 'small',
        galaxy: 'design',
        links: { github: 'https://github.com/forbiddenlink/coding-jokes' },
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'goodstuff-foodtruck',
        title: 'Goodstuff Food Truck',
        description: 'Vibrant food truck website with online ordering, menu showcase, location tracking, and modern responsive design. Full e-commerce flow.',
        role: 'Creator',
        tags: ['Next.js', 'E-commerce', 'Responsive', 'Food Service'],
        color: '#FF006E',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'design',
        links: { live: 'https://goodstuff-foodtruck.vercel.app' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
  {
    id: 'experimental',
    name: 'Experimental Zone',
    description: 'Side projects and creative experiments',
    color: '#FFB800',
    size: 1,
    projects: [
      {
        id: 'blackjack',
        title: 'Blackjack Game',
        description: 'Interactive blackjack game with React, card animations, and betting system.',
        role: 'Creator',
        tags: ['Game', 'React', 'Logic'],
        color: '#FFB800',
        brightness: 1.2,
        size: 'small',
        galaxy: 'experimental',
        links: { github: 'https://github.com/forbiddenlink/blackjack-game' },
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'pixelforge',
        title: 'PixelForge Test',
        description: 'Pixel manipulation and generative art experiment.',
        role: 'Creator',
        tags: ['Generative Art', 'Canvas', 'Experiment'],
        color: '#FFB800',
        brightness: 1.0,
        size: 'small',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2023',
      },
      {
        id: 'ocean-simulator',
        title: 'Ocean Ecosystem Simulator',
        description: 'Cutting-edge ocean ecosystem simulator with complex food chains, realistic physics, and emergent behaviors - rivaling AAA game engines in the browser.',
        role: 'Creator',
        tags: ['WebGL', 'Three.js', 'Simulation', 'Physics'],
        color: '#0EA5E9',
        brightness: 1.8,
        size: 'large',
        galaxy: 'experimental',
        featured: true,
        dateRange: '2024',
      },
      {
        id: 'plant-therapy',
        title: 'Plant Therapy Blog',
        description: 'Responsive blog website focused on plant care and mental wellness with modern dark mode and Tailwind CSS.',
        role: 'Creator',
        tags: ['Blog', 'Tailwind CSS', 'Responsive'],
        color: '#84CC16',
        brightness: 1.1,
        size: 'small',
        galaxy: 'experimental',
        links: { live: 'https://plant-therapy.vercel.app' },
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'aegis-audit',
        title: 'AegisAudit',
        description: 'Comprehensive security audit tool for web applications with vulnerability scanning and compliance reporting.',
        role: 'Creator',
        tags: ['Security', 'Audit', 'TypeScript', 'Compliance'],
        color: '#FFB800',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'experimental',
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'chronicle',
        title: 'Chronicle',
        description: 'Interactive timeline and history visualization app for documenting personal or project milestones.',
        role: 'Creator',
        tags: ['Timeline', 'Visualization', 'History', 'React'],
        color: '#FFB800',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2024',
      },
      {
        id: 'mythos',
        title: 'Mythos',
        description: 'Interactive storytelling platform exploring mythology and folklore with rich narrative experiences.',
        role: 'Creator',
        tags: ['Storytelling', 'Interactive', 'Mythology', 'React'],
        color: '#FFB800',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'timeslip-search',
        title: 'TimeSlipSearch',
        description: 'Conversational cultural time machine exploring 1958-2020 with 420,000+ records (Billboard, TMDB, FRED, Wikimedia). Voice search, achievements, Time Capsule Wrapped analytics, retro CRT interface.',
        role: 'Creator',
        tags: ['Next.js 16', 'Algolia', 'Chart.js', 'Framer Motion'],
        color: '#FFB800',
        brightness: 1.7,
        size: 'large',
        galaxy: 'experimental',
        links: { live: 'https://timeslipsearch.vercel.app' },
        metrics: { files: 420000 },
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'apoc-bnb',
        title: 'Apoc BnB',
        description: 'Post-apocalyptic Airbnb parody with Mapbox integration, AI chatbot, dynamic pricing, neobrutal design system with radioactive green theme. Full test coverage with Vitest.',
        role: 'Creator',
        tags: ['Next.js 16', 'Mapbox', 'Zustand', 'Framer Motion', 'Vitest'],
        color: '#FFB800',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'cereal-tasting',
        title: 'Cereal Tasting',
        description: 'Fun cereal review and rating app with detailed tasting notes and rankings.',
        role: 'Creator',
        tags: ['Fun', 'Reviews', 'React', 'Database'],
        color: '#FFB800',
        brightness: 1.1,
        size: 'small',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2025',
      },

      {
        id: 'competitor-stalker',
        title: 'Competitor Stalker',
        description: 'Competitive analysis tool for tracking competitor websites, features, and market positioning.',
        role: 'Creator',
        tags: ['Analysis', 'Marketing', 'Scraping', 'Dashboard'],
        color: '#FFB800',
        brightness: 1.4,
        size: 'medium',
        galaxy: 'experimental',
        featured: false,
        dateRange: '2025',
      },
      {
        id: 'pollyglot',
        title: 'Pollyglot',
        description: 'Language learning platform with spaced repetition, pronunciation practice, and gamification.',
        role: 'Creator',
        tags: ['Education', 'Languages', 'Gamification', 'Next.js'],
        color: '#FFB800',
        brightness: 1.5,
        size: 'medium',
        galaxy: 'experimental',
        links: { live: 'https://pollyglot.vercel.app' },
        featured: true,
        dateRange: '2025',
      },
      {
        id: 'guts-and-glory',
        title: 'Guts & Glory',
        description: 'Bold, irreverent content platform showcasing creative storytelling with distinctive visual design and interactive elements.',
        role: 'Creator',
        tags: ['Creative', 'Content', 'Design', 'Next.js'],
        color: '#DC2626',
        brightness: 1.3,
        size: 'medium',
        galaxy: 'experimental',
        links: { live: 'https://guts-and-glory.vercel.app' },
        featured: false,
        dateRange: '2025',
      },
    ],
  },
]

// Helper to get all projects flattened
export const allProjects = galaxies.flatMap((g) => g.projects)

// Helper to get featured projects
export const featuredProjects = allProjects.filter((p) => p.featured)

// Helper to get project by ID
export function getProjectById(id: string) {
  return allProjects.find((p) => p.id === id)
}

// Helper to get galaxy by ID
export function getGalaxyById(id: string) {
  return galaxies.find((g) => g.id === id)
}
